name: CI

on:
    push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Run a multi-line script with an error
      run: |
        echo This will fail
        echo "this is a secret: $MY_SECRET"
        echo "This should not be printed in logs"
        echo "This is actor: $GITHUB_ACTOR"
        exit 0
      env:
        MY_SECRET: "THis is a secret value that should not be exposed in logs"