name: CI

run-name: Main Workflow

on:
    issue_comment:
        types: [created, deleted, edited]
    pull_request:
        types: [opened, synchronize, closed, reopened, edited, locked]
    push:
        branches:
            - main

jobs:
    A:
        runs-on: ubuntu-latest
        steps:
            - name: run a script
              run: echo "This is job A" && echo "$VAR1 $VAR2"
              env:
                VAR1: value1
                VAR2: value2