name: CI

run-name: Main Workflow

on:
    issue_comment:
        types: [created, deleted, edited]
    pull_request:
        types: [opened, synchronize, closed, reopened, edited, locked]
    push:
        branches:
            - main

jobs:
    A:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: list_all_files
              run: ls -ltra
            - name: Run a script
              run: echo ${{ env.GREETING }}
              env:
                    GREETING: "Hello World"